[env:feather_m0]
platform = atmelsam
board = adafruit_feather_m0
framework = arduino
monitor_speed = 57600
lib_deps =
  adafruit/Adafruit Motor Shield V2 Library @ ^1.1.0
  adafruit/Adafruit ADS1X15 @ ^2.4.0
  adafruit/Adafruit BusIO @ ^1.14
  nanopb/Nanopb @ ^0.4.8
lib_ldf_mode = deep+
