/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DELTA_ARRAY_PB_H_INCLUDED
#define PB_DELTA_ARRAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Acceptance ACK for JointFrame commands. Sent by the addressed board
 immediately after the command is parsed and validated. It reports whether
 the command was accepted; it does NOT report move completion (completion
 is still polled via StatusFrame.done_req). */
typedef enum _AckStatus {
    AckStatus_ACK_OK = 0,
    AckStatus_ACK_VALIDATION_FAIL = 1, /* joint_pos count wrong, traj dims invalid, etc. */
    AckStatus_ACK_UNKNOWN_COMMAND = 2 /* unrecognized JointFrame.kind variant */
} AckStatus;

/* Struct definitions */
typedef struct _PoseRequest {
    char dummy_field;
} PoseRequest;

typedef struct _DoneRequest {
    char dummy_field;
} DoneRequest;

typedef struct _PoseResponse {
    pb_size_t joint_pos_count;
    float joint_pos[12];
} PoseResponse;

typedef struct _DoneResponse {
    bool done;
} DoneResponse;

/* Whoami: the host asks a board for its chip-derived id (id_req) and the board
 answers with it (id_resp). Used for discovery — the host addresses id_req to
 the broadcast id (0) when it does not yet know the board's real id. */
typedef struct _IdRequest {
    char dummy_field;
} IdRequest;

typedef struct _IdResponse {
    uint32_t id;
} IdResponse;

/* Diagnostics telemetry: the host asks for per-motor control state (telemetry_req)
 and the board answers (telemetry_resp) with position, PID error, and the last
 applied signed PWM for all 12 motors. Used to characterize the motors (e.g.
 breakaway friction, open-loop velocity) and to observe closed-loop moves. */
typedef struct _TelemetryRequest {
    char dummy_field;
} TelemetryRequest;

typedef struct _TelemetryResponse {
    pb_size_t position_count;
    float position[12]; /* 12, meters */
    pb_size_t error_count;
    float error[12]; /* 12, meters (joint_positions - target) */
    pb_size_t pwm_count;
    int32_t pwm[12]; /* 12, last applied signed PWM (-255..255, 0 = released) */
} TelemetryResponse;

/* Config readback: the host asks a board for its live tuning (config_req) and
 the board answers (config_resp) with the current per-motor deadband/bias and
 the board-global brake mode. SetConfigCommand is otherwise write-only, so this
 is the only way to verify what a board is actually running -- important
 because the config is RAM-only and reverts to the compiled defaults on reboot. */
typedef struct _ConfigRequest {
    char dummy_field;
} ConfigRequest;

typedef struct _ConfigResponse {
    pb_size_t deadband_count;
    float deadband[12]; /* 12, meters */
    pb_size_t bias_fwd_count;
    int32_t bias_fwd[12]; /* 12, static feedforward PWM (FORWARD) */
    pb_size_t bias_back_count;
    int32_t bias_back[12]; /* 12, static feedforward PWM (BACKWARD) */
    bool brake_at_setpoint; /* board-global: brake (true) vs coast at setpoint */
} ConfigResponse;

typedef struct _StatusFrame {
    pb_size_t which_kind;
    union {
        PoseRequest pose_req;
        DoneRequest done_req;
        PoseResponse pose_resp;
        DoneResponse done_resp;
        IdRequest id_req;
        IdResponse id_resp;
        TelemetryRequest telemetry_req;
        TelemetryResponse telemetry_resp;
        ConfigRequest config_req;
        ConfigResponse config_resp;
    } kind;
} StatusFrame;

typedef struct _MoveCommand {
    pb_size_t joint_pos_count;
    float joint_pos[12];
} MoveCommand;

typedef struct _TrajectoryCommand {
    pb_size_t joint_pos_count;
    float joint_pos[240];
} TrajectoryCommand;

typedef struct _ResetCommand {
    char dummy_field;
} ResetCommand;

typedef struct _StopCommand {
    char dummy_field;
} StopCommand;

/* Open-loop diagnostics: drive a single motor at a fixed PWM, bypassing the PID.
 The board releases all other motors first (so this never fights the PID) and
 auto-releases the driven motor after duration_ms (a safety timeout, so a lost
 host can't leave a motor driven). Used to measure static-friction breakaway
 and open-loop velocity vs PWM. */
typedef struct _SetPwmCommand {
    uint32_t motor_index; /* 0..11 */
    int32_t pwm; /* signed: sign = direction, |pwm| clamped to 0..255 */
    uint32_t duration_ms; /* auto-release after this; 0 => default, clamped to the move timeout */
} SetPwmCommand;

/* Runtime per-motor tuning. Overwrites the board's compiled defaults for the
 addressed motor(s) without reflashing, so a single firmware image can carry
 safe defaults while each physical board is calibrated from a host-side JSON
 (keyed by board id) pushed after connecting. Fields are proto3 `optional`, so
 a command may set only some of them; absent fields are left unchanged. */
typedef struct _SetConfigCommand {
    bool has_motor_index;
    uint32_t motor_index; /* 0..11; absent => apply to all motors */
    bool has_deadband;
    float deadband; /* meters; |err| below this counts as settled */
    bool has_bias_fwd;
    int32_t bias_fwd; /* static feedforward PWM, FORWARD branch (0..255) */
    bool has_bias_back;
    int32_t bias_back; /* static feedforward PWM, BACKWARD branch (0..255) */
    /* Board-global (ignores motor_index): when true, a joint that reaches its
 setpoint short-brakes instead of coasting (RELEASE), arresting the ~2-3 mm
 post-release overshoot. Default false = original coast-at-setpoint behavior. */
    bool has_brake_at_setpoint;
    bool brake_at_setpoint;
} SetConfigCommand;

typedef struct _JointFrame {
    pb_size_t which_kind;
    union {
        MoveCommand move;
        TrajectoryCommand traj;
        ResetCommand reset;
        StopCommand stop;
        SetPwmCommand set_pwm;
        SetConfigCommand set_config;
    } kind;
} JointFrame;

typedef struct _CommandAck {
    AckStatus status;
} CommandAck;

typedef struct _DeltaMessage {
    int32_t id;
    pb_size_t which_payload;
    union {
        StatusFrame status;
        JointFrame joint;
        CommandAck ack;
    } payload;
} DeltaMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AckStatus_MIN AckStatus_ACK_OK
#define _AckStatus_MAX AckStatus_ACK_UNKNOWN_COMMAND
#define _AckStatus_ARRAYSIZE ((AckStatus)(AckStatus_ACK_UNKNOWN_COMMAND+1))



















#define CommandAck_status_ENUMTYPE AckStatus



/* Initializer values for message structs */
#define PoseRequest_init_default                 {0}
#define DoneRequest_init_default                 {0}
#define PoseResponse_init_default                {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define DoneResponse_init_default                {0}
#define IdRequest_init_default                   {0}
#define IdResponse_init_default                  {0}
#define TelemetryRequest_init_default            {0}
#define TelemetryResponse_init_default           {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define ConfigRequest_init_default               {0}
#define ConfigResponse_init_default              {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define StatusFrame_init_default                 {0, {PoseRequest_init_default}}
#define MoveCommand_init_default                 {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define TrajectoryCommand_init_default           {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define ResetCommand_init_default                {0}
#define StopCommand_init_default                 {0}
#define SetPwmCommand_init_default               {0, 0, 0}
#define SetConfigCommand_init_default            {false, 0, false, 0, false, 0, false, 0, false, 0}
#define JointFrame_init_default                  {0, {MoveCommand_init_default}}
#define CommandAck_init_default                  {_AckStatus_MIN}
#define DeltaMessage_init_default                {0, 0, {StatusFrame_init_default}}
#define PoseRequest_init_zero                    {0}
#define DoneRequest_init_zero                    {0}
#define PoseResponse_init_zero                   {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define DoneResponse_init_zero                   {0}
#define IdRequest_init_zero                      {0}
#define IdResponse_init_zero                     {0}
#define TelemetryRequest_init_zero               {0}
#define TelemetryResponse_init_zero              {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define ConfigRequest_init_zero                  {0}
#define ConfigResponse_init_zero                 {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0}
#define StatusFrame_init_zero                    {0, {PoseRequest_init_zero}}
#define MoveCommand_init_zero                    {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define TrajectoryCommand_init_zero              {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define ResetCommand_init_zero                   {0}
#define StopCommand_init_zero                    {0}
#define SetPwmCommand_init_zero                  {0, 0, 0}
#define SetConfigCommand_init_zero               {false, 0, false, 0, false, 0, false, 0, false, 0}
#define JointFrame_init_zero                     {0, {MoveCommand_init_zero}}
#define CommandAck_init_zero                     {_AckStatus_MIN}
#define DeltaMessage_init_zero                   {0, 0, {StatusFrame_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define PoseResponse_joint_pos_tag               1
#define DoneResponse_done_tag                    1
#define IdResponse_id_tag                        1
#define TelemetryResponse_position_tag           1
#define TelemetryResponse_error_tag              2
#define TelemetryResponse_pwm_tag                3
#define ConfigResponse_deadband_tag              1
#define ConfigResponse_bias_fwd_tag              2
#define ConfigResponse_bias_back_tag             3
#define ConfigResponse_brake_at_setpoint_tag     4
#define StatusFrame_pose_req_tag                 1
#define StatusFrame_done_req_tag                 2
#define StatusFrame_pose_resp_tag                3
#define StatusFrame_done_resp_tag                4
#define StatusFrame_id_req_tag                   5
#define StatusFrame_id_resp_tag                  6
#define StatusFrame_telemetry_req_tag            7
#define StatusFrame_telemetry_resp_tag           8
#define StatusFrame_config_req_tag               9
#define StatusFrame_config_resp_tag              10
#define MoveCommand_joint_pos_tag                1
#define TrajectoryCommand_joint_pos_tag          1
#define SetPwmCommand_motor_index_tag            1
#define SetPwmCommand_pwm_tag                    2
#define SetPwmCommand_duration_ms_tag            3
#define SetConfigCommand_motor_index_tag         1
#define SetConfigCommand_deadband_tag            2
#define SetConfigCommand_bias_fwd_tag            3
#define SetConfigCommand_bias_back_tag           4
#define SetConfigCommand_brake_at_setpoint_tag   5
#define JointFrame_move_tag                      1
#define JointFrame_traj_tag                      2
#define JointFrame_reset_tag                     3
#define JointFrame_stop_tag                      4
#define JointFrame_set_pwm_tag                   5
#define JointFrame_set_config_tag                6
#define CommandAck_status_tag                    1
#define DeltaMessage_id_tag                      1
#define DeltaMessage_status_tag                  2
#define DeltaMessage_joint_tag                   3
#define DeltaMessage_ack_tag                     4

/* Struct field encoding specification for nanopb */
#define PoseRequest_FIELDLIST(X, a) \

#define PoseRequest_CALLBACK NULL
#define PoseRequest_DEFAULT NULL

#define DoneRequest_FIELDLIST(X, a) \

#define DoneRequest_CALLBACK NULL
#define DoneRequest_DEFAULT NULL

#define PoseResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    joint_pos,         1)
#define PoseResponse_CALLBACK NULL
#define PoseResponse_DEFAULT NULL

#define DoneResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     done,              1)
#define DoneResponse_CALLBACK NULL
#define DoneResponse_DEFAULT NULL

#define IdRequest_FIELDLIST(X, a) \

#define IdRequest_CALLBACK NULL
#define IdRequest_DEFAULT NULL

#define IdResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1)
#define IdResponse_CALLBACK NULL
#define IdResponse_DEFAULT NULL

#define TelemetryRequest_FIELDLIST(X, a) \

#define TelemetryRequest_CALLBACK NULL
#define TelemetryRequest_DEFAULT NULL

#define TelemetryResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    position,          1) \
X(a, STATIC,   REPEATED, FLOAT,    error,             2) \
X(a, STATIC,   REPEATED, SINT32,   pwm,               3)
#define TelemetryResponse_CALLBACK NULL
#define TelemetryResponse_DEFAULT NULL

#define ConfigRequest_FIELDLIST(X, a) \

#define ConfigRequest_CALLBACK NULL
#define ConfigRequest_DEFAULT NULL

#define ConfigResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    deadband,          1) \
X(a, STATIC,   REPEATED, SINT32,   bias_fwd,          2) \
X(a, STATIC,   REPEATED, SINT32,   bias_back,         3) \
X(a, STATIC,   SINGULAR, BOOL,     brake_at_setpoint,   4)
#define ConfigResponse_CALLBACK NULL
#define ConfigResponse_DEFAULT NULL

#define StatusFrame_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,pose_req,kind.pose_req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,done_req,kind.done_req),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,pose_resp,kind.pose_resp),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,done_resp,kind.done_resp),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,id_req,kind.id_req),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,id_resp,kind.id_resp),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,telemetry_req,kind.telemetry_req),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,telemetry_resp,kind.telemetry_resp),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,config_req,kind.config_req),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,config_resp,kind.config_resp),  10)
#define StatusFrame_CALLBACK NULL
#define StatusFrame_DEFAULT NULL
#define StatusFrame_kind_pose_req_MSGTYPE PoseRequest
#define StatusFrame_kind_done_req_MSGTYPE DoneRequest
#define StatusFrame_kind_pose_resp_MSGTYPE PoseResponse
#define StatusFrame_kind_done_resp_MSGTYPE DoneResponse
#define StatusFrame_kind_id_req_MSGTYPE IdRequest
#define StatusFrame_kind_id_resp_MSGTYPE IdResponse
#define StatusFrame_kind_telemetry_req_MSGTYPE TelemetryRequest
#define StatusFrame_kind_telemetry_resp_MSGTYPE TelemetryResponse
#define StatusFrame_kind_config_req_MSGTYPE ConfigRequest
#define StatusFrame_kind_config_resp_MSGTYPE ConfigResponse

#define MoveCommand_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    joint_pos,         1)
#define MoveCommand_CALLBACK NULL
#define MoveCommand_DEFAULT NULL

#define TrajectoryCommand_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    joint_pos,         1)
#define TrajectoryCommand_CALLBACK NULL
#define TrajectoryCommand_DEFAULT NULL

#define ResetCommand_FIELDLIST(X, a) \

#define ResetCommand_CALLBACK NULL
#define ResetCommand_DEFAULT NULL

#define StopCommand_FIELDLIST(X, a) \

#define StopCommand_CALLBACK NULL
#define StopCommand_DEFAULT NULL

#define SetPwmCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   motor_index,       1) \
X(a, STATIC,   SINGULAR, SINT32,   pwm,               2) \
X(a, STATIC,   SINGULAR, UINT32,   duration_ms,       3)
#define SetPwmCommand_CALLBACK NULL
#define SetPwmCommand_DEFAULT NULL

#define SetConfigCommand_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   motor_index,       1) \
X(a, STATIC,   OPTIONAL, FLOAT,    deadband,          2) \
X(a, STATIC,   OPTIONAL, SINT32,   bias_fwd,          3) \
X(a, STATIC,   OPTIONAL, SINT32,   bias_back,         4) \
X(a, STATIC,   OPTIONAL, BOOL,     brake_at_setpoint,   5)
#define SetConfigCommand_CALLBACK NULL
#define SetConfigCommand_DEFAULT NULL

#define JointFrame_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,move,kind.move),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,traj,kind.traj),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,reset,kind.reset),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,stop,kind.stop),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,set_pwm,kind.set_pwm),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,set_config,kind.set_config),   6)
#define JointFrame_CALLBACK NULL
#define JointFrame_DEFAULT NULL
#define JointFrame_kind_move_MSGTYPE MoveCommand
#define JointFrame_kind_traj_MSGTYPE TrajectoryCommand
#define JointFrame_kind_reset_MSGTYPE ResetCommand
#define JointFrame_kind_stop_MSGTYPE StopCommand
#define JointFrame_kind_set_pwm_MSGTYPE SetPwmCommand
#define JointFrame_kind_set_config_MSGTYPE SetConfigCommand

#define CommandAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1)
#define CommandAck_CALLBACK NULL
#define CommandAck_DEFAULT NULL

#define DeltaMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,joint,payload.joint),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   4)
#define DeltaMessage_CALLBACK NULL
#define DeltaMessage_DEFAULT NULL
#define DeltaMessage_payload_status_MSGTYPE StatusFrame
#define DeltaMessage_payload_joint_MSGTYPE JointFrame
#define DeltaMessage_payload_ack_MSGTYPE CommandAck

extern const pb_msgdesc_t PoseRequest_msg;
extern const pb_msgdesc_t DoneRequest_msg;
extern const pb_msgdesc_t PoseResponse_msg;
extern const pb_msgdesc_t DoneResponse_msg;
extern const pb_msgdesc_t IdRequest_msg;
extern const pb_msgdesc_t IdResponse_msg;
extern const pb_msgdesc_t TelemetryRequest_msg;
extern const pb_msgdesc_t TelemetryResponse_msg;
extern const pb_msgdesc_t ConfigRequest_msg;
extern const pb_msgdesc_t ConfigResponse_msg;
extern const pb_msgdesc_t StatusFrame_msg;
extern const pb_msgdesc_t MoveCommand_msg;
extern const pb_msgdesc_t TrajectoryCommand_msg;
extern const pb_msgdesc_t ResetCommand_msg;
extern const pb_msgdesc_t StopCommand_msg;
extern const pb_msgdesc_t SetPwmCommand_msg;
extern const pb_msgdesc_t SetConfigCommand_msg;
extern const pb_msgdesc_t JointFrame_msg;
extern const pb_msgdesc_t CommandAck_msg;
extern const pb_msgdesc_t DeltaMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PoseRequest_fields &PoseRequest_msg
#define DoneRequest_fields &DoneRequest_msg
#define PoseResponse_fields &PoseResponse_msg
#define DoneResponse_fields &DoneResponse_msg
#define IdRequest_fields &IdRequest_msg
#define IdResponse_fields &IdResponse_msg
#define TelemetryRequest_fields &TelemetryRequest_msg
#define TelemetryResponse_fields &TelemetryResponse_msg
#define ConfigRequest_fields &ConfigRequest_msg
#define ConfigResponse_fields &ConfigResponse_msg
#define StatusFrame_fields &StatusFrame_msg
#define MoveCommand_fields &MoveCommand_msg
#define TrajectoryCommand_fields &TrajectoryCommand_msg
#define ResetCommand_fields &ResetCommand_msg
#define StopCommand_fields &StopCommand_msg
#define SetPwmCommand_fields &SetPwmCommand_msg
#define SetConfigCommand_fields &SetConfigCommand_msg
#define JointFrame_fields &JointFrame_msg
#define CommandAck_fields &CommandAck_msg
#define DeltaMessage_fields &DeltaMessage_msg

/* Maximum encoded size of messages (where known) */
#define CommandAck_size                          2
#define ConfigRequest_size                       0
#define ConfigResponse_size                      206
#define DELTA_ARRAY_PB_H_MAX_SIZE                DeltaMessage_size
#define DeltaMessage_size                        1217
#define DoneRequest_size                         0
#define DoneResponse_size                        2
#define IdRequest_size                           0
#define IdResponse_size                          6
#define JointFrame_size                          1203
#define MoveCommand_size                         60
#define PoseRequest_size                         0
#define PoseResponse_size                        60
#define ResetCommand_size                        0
#define SetConfigCommand_size                    25
#define SetPwmCommand_size                       18
#define StatusFrame_size                         209
#define StopCommand_size                         0
#define TelemetryRequest_size                    0
#define TelemetryResponse_size                   192
#define TrajectoryCommand_size                   1200

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
