/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "delta_array.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PoseRequest, PoseRequest, AUTO)


PB_BIND(DoneRequest, DoneRequest, AUTO)


PB_BIND(PoseResponse, PoseResponse, AUTO)


PB_BIND(DoneResponse, DoneResponse, AUTO)


PB_BIND(IdRequest, IdRequest, AUTO)


PB_BIND(IdResponse, IdResponse, AUTO)


PB_BIND(StatusFrame, StatusFrame, AUTO)


PB_BIND(MoveCommand, MoveCommand, AUTO)


PB_BIND(TrajectoryCommand, TrajectoryCommand, 2)


PB_BIND(ResetCommand, ResetCommand, AUTO)


PB_BIND(StopCommand, StopCommand, AUTO)


PB_BIND(JointFrame, JointFrame, 2)


PB_BIND(CommandAck, CommandAck, AUTO)


PB_BIND(DeltaMessage, DeltaMessage, 2)





