/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DELTA_ARRAY_PB_H_INCLUDED
#define PB_DELTA_ARRAY_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Acceptance ACK for JointFrame commands. Sent by the addressed board
 immediately after the command is parsed and validated. It reports whether
 the command was accepted; it does NOT report move completion (completion
 is still polled via StatusFrame.done_req). */
typedef enum _AckStatus {
    AckStatus_ACK_OK = 0,
    AckStatus_ACK_VALIDATION_FAIL = 1, /* joint_pos count wrong, traj dims invalid, etc. */
    AckStatus_ACK_UNKNOWN_COMMAND = 2 /* unrecognized JointFrame.kind variant */
} AckStatus;

/* Struct definitions */
typedef struct _PoseRequest {
    char dummy_field;
} PoseRequest;

typedef struct _DoneRequest {
    char dummy_field;
} DoneRequest;

typedef struct _PoseResponse {
    pb_size_t joint_pos_count;
    float joint_pos[12];
} PoseResponse;

typedef struct _DoneResponse {
    bool done;
} DoneResponse;

typedef struct _StatusFrame {
    pb_size_t which_kind;
    union {
        PoseRequest pose_req;
        DoneRequest done_req;
        PoseResponse pose_resp;
        DoneResponse done_resp;
    } kind;
} StatusFrame;

typedef struct _MoveCommand {
    pb_size_t joint_pos_count;
    float joint_pos[12];
} MoveCommand;

typedef struct _TrajectoryCommand {
    pb_size_t joint_pos_count;
    float joint_pos[240];
} TrajectoryCommand;

typedef struct _ResetCommand {
    char dummy_field;
} ResetCommand;

typedef struct _StopCommand {
    char dummy_field;
} StopCommand;

typedef struct _JointFrame {
    pb_size_t which_kind;
    union {
        MoveCommand move;
        TrajectoryCommand traj;
        ResetCommand reset;
        StopCommand stop;
    } kind;
} JointFrame;

typedef struct _CommandAck {
    AckStatus status;
} CommandAck;

typedef struct _DeltaMessage {
    int32_t id;
    pb_size_t which_payload;
    union {
        StatusFrame status;
        JointFrame joint;
        CommandAck ack;
    } payload;
} DeltaMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AckStatus_MIN AckStatus_ACK_OK
#define _AckStatus_MAX AckStatus_ACK_UNKNOWN_COMMAND
#define _AckStatus_ARRAYSIZE ((AckStatus)(AckStatus_ACK_UNKNOWN_COMMAND+1))











#define CommandAck_status_ENUMTYPE AckStatus



/* Initializer values for message structs */
#define PoseRequest_init_default                 {0}
#define DoneRequest_init_default                 {0}
#define PoseResponse_init_default                {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define DoneResponse_init_default                {0}
#define StatusFrame_init_default                 {0, {PoseRequest_init_default}}
#define MoveCommand_init_default                 {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define TrajectoryCommand_init_default           {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define ResetCommand_init_default                {0}
#define StopCommand_init_default                 {0}
#define JointFrame_init_default                  {0, {MoveCommand_init_default}}
#define CommandAck_init_default                  {_AckStatus_MIN}
#define DeltaMessage_init_default                {0, 0, {StatusFrame_init_default}}
#define PoseRequest_init_zero                    {0}
#define DoneRequest_init_zero                    {0}
#define PoseResponse_init_zero                   {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define DoneResponse_init_zero                   {0}
#define StatusFrame_init_zero                    {0, {PoseRequest_init_zero}}
#define MoveCommand_init_zero                    {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define TrajectoryCommand_init_zero              {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define ResetCommand_init_zero                   {0}
#define StopCommand_init_zero                    {0}
#define JointFrame_init_zero                     {0, {MoveCommand_init_zero}}
#define CommandAck_init_zero                     {_AckStatus_MIN}
#define DeltaMessage_init_zero                   {0, 0, {StatusFrame_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define PoseResponse_joint_pos_tag               1
#define DoneResponse_done_tag                    1
#define StatusFrame_pose_req_tag                 1
#define StatusFrame_done_req_tag                 2
#define StatusFrame_pose_resp_tag                3
#define StatusFrame_done_resp_tag                4
#define MoveCommand_joint_pos_tag                1
#define TrajectoryCommand_joint_pos_tag          1
#define JointFrame_move_tag                      1
#define JointFrame_traj_tag                      2
#define JointFrame_reset_tag                     3
#define JointFrame_stop_tag                      4
#define CommandAck_status_tag                    1
#define DeltaMessage_id_tag                      1
#define DeltaMessage_status_tag                  2
#define DeltaMessage_joint_tag                   3
#define DeltaMessage_ack_tag                     4

/* Struct field encoding specification for nanopb */
#define PoseRequest_FIELDLIST(X, a) \

#define PoseRequest_CALLBACK NULL
#define PoseRequest_DEFAULT NULL

#define DoneRequest_FIELDLIST(X, a) \

#define DoneRequest_CALLBACK NULL
#define DoneRequest_DEFAULT NULL

#define PoseResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    joint_pos,         1)
#define PoseResponse_CALLBACK NULL
#define PoseResponse_DEFAULT NULL

#define DoneResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     done,              1)
#define DoneResponse_CALLBACK NULL
#define DoneResponse_DEFAULT NULL

#define StatusFrame_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,pose_req,kind.pose_req),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,done_req,kind.done_req),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,pose_resp,kind.pose_resp),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,done_resp,kind.done_resp),   4)
#define StatusFrame_CALLBACK NULL
#define StatusFrame_DEFAULT NULL
#define StatusFrame_kind_pose_req_MSGTYPE PoseRequest
#define StatusFrame_kind_done_req_MSGTYPE DoneRequest
#define StatusFrame_kind_pose_resp_MSGTYPE PoseResponse
#define StatusFrame_kind_done_resp_MSGTYPE DoneResponse

#define MoveCommand_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    joint_pos,         1)
#define MoveCommand_CALLBACK NULL
#define MoveCommand_DEFAULT NULL

#define TrajectoryCommand_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, FLOAT,    joint_pos,         1)
#define TrajectoryCommand_CALLBACK NULL
#define TrajectoryCommand_DEFAULT NULL

#define ResetCommand_FIELDLIST(X, a) \

#define ResetCommand_CALLBACK NULL
#define ResetCommand_DEFAULT NULL

#define StopCommand_FIELDLIST(X, a) \

#define StopCommand_CALLBACK NULL
#define StopCommand_DEFAULT NULL

#define JointFrame_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,move,kind.move),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,traj,kind.traj),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,reset,kind.reset),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (kind,stop,kind.stop),   4)
#define JointFrame_CALLBACK NULL
#define JointFrame_DEFAULT NULL
#define JointFrame_kind_move_MSGTYPE MoveCommand
#define JointFrame_kind_traj_MSGTYPE TrajectoryCommand
#define JointFrame_kind_reset_MSGTYPE ResetCommand
#define JointFrame_kind_stop_MSGTYPE StopCommand

#define CommandAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    status,            1)
#define CommandAck_CALLBACK NULL
#define CommandAck_DEFAULT NULL

#define DeltaMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,status,payload.status),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,joint,payload.joint),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (payload,ack,payload.ack),   4)
#define DeltaMessage_CALLBACK NULL
#define DeltaMessage_DEFAULT NULL
#define DeltaMessage_payload_status_MSGTYPE StatusFrame
#define DeltaMessage_payload_joint_MSGTYPE JointFrame
#define DeltaMessage_payload_ack_MSGTYPE CommandAck

extern const pb_msgdesc_t PoseRequest_msg;
extern const pb_msgdesc_t DoneRequest_msg;
extern const pb_msgdesc_t PoseResponse_msg;
extern const pb_msgdesc_t DoneResponse_msg;
extern const pb_msgdesc_t StatusFrame_msg;
extern const pb_msgdesc_t MoveCommand_msg;
extern const pb_msgdesc_t TrajectoryCommand_msg;
extern const pb_msgdesc_t ResetCommand_msg;
extern const pb_msgdesc_t StopCommand_msg;
extern const pb_msgdesc_t JointFrame_msg;
extern const pb_msgdesc_t CommandAck_msg;
extern const pb_msgdesc_t DeltaMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PoseRequest_fields &PoseRequest_msg
#define DoneRequest_fields &DoneRequest_msg
#define PoseResponse_fields &PoseResponse_msg
#define DoneResponse_fields &DoneResponse_msg
#define StatusFrame_fields &StatusFrame_msg
#define MoveCommand_fields &MoveCommand_msg
#define TrajectoryCommand_fields &TrajectoryCommand_msg
#define ResetCommand_fields &ResetCommand_msg
#define StopCommand_fields &StopCommand_msg
#define JointFrame_fields &JointFrame_msg
#define CommandAck_fields &CommandAck_msg
#define DeltaMessage_fields &DeltaMessage_msg

/* Maximum encoded size of messages (where known) */
#define CommandAck_size                          2
#define DELTA_ARRAY_PB_H_MAX_SIZE                DeltaMessage_size
#define DeltaMessage_size                        1217
#define DoneRequest_size                         0
#define DoneResponse_size                        2
#define JointFrame_size                          1203
#define MoveCommand_size                         60
#define PoseRequest_size                         0
#define PoseResponse_size                        60
#define ResetCommand_size                        0
#define StatusFrame_size                         62
#define StopCommand_size                         0
#define TrajectoryCommand_size                   1200

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
